# Generated by Django 4.0.6 on 2022-07-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('keyboard', 'teclado'), ('mouse', 'raton'), ('monitor', 'monitor'), ('speaker', 'altavoz'), ('motherboard', 'placa'), ('processor', 'procesador')], max_length=20, null=True)),
                ('brand', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('keyboard', 'teclado'), ('mouse', 'raton'), ('monitor', 'monitor'), ('speaker', 'altavoz'), ('motherboard', 'placa'), ('processor', 'procesador')], max_length=20, null=True)),
                ('brand', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=100, unique=True)),
                ('total_cost_order', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutputDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('keyboard', 'teclado'), ('mouse', 'raton'), ('monitor', 'monitor'), ('speaker', 'altavoz'), ('motherboard', 'placa'), ('processor', 'procesador')], max_length=20, null=True)),
                ('brand', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('inputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computadora_app.inputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('descriptoin', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('computadora_app.inputdevice',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('outputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computadora_app.outputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('descriptoin', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('computadora_app.outputdevice',),
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('internaldevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computadora_app.internaldevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('descriptoin', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('computadora_app.internaldevice',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('inputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computadora_app.inputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('descriptoin', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('computadora_app.inputdevice',),
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('internaldevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computadora_app.internaldevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('descriptoin', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('computadora_app.internaldevice',),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('outputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computadora_app.outputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('descriptoin', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('computadora_app.outputdevice',),
        ),
        migrations.CreateModel(
            name='OrderDetailComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_cost_order', models.FloatField(blank=True, null=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computadora_app.computer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computadora_app.order')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='keyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computadora_app.keyboard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computadora_app.monitor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computadora_app.motherboard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computadora_app.mouse'),
        ),
        migrations.AddField(
            model_name='computer',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computadora_app.processor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computadora_app.speaker'),
        ),
    ]
